### ISSUE TITLE
[문의-아하하] 암호화폐 자동매매 시스템 만들기 with 파이썬 - 6장 리뷰 #1

### ISSUE THREAD

**Issue by johnverkim** [jhonverkim/smtm#1]
> 안녕하세요. 6장을 주피터 노트북을 이용해서 실습 중입니다. 토큰 만들고 계좌 조회까진 다 되는데 시장 가격 매수 주문부터 문제가 생깁니다. 저는 업비트 키를 전부 넣고 해서 제 계좌 정보까지는 정상적으로 받았습니다. 시장가격 매수부터는 오류 메시지도 출력되지않고  []만 반환합니다. 업비트 계정을 확인해보니 거래 요청도 되지 않았습니다. 뭐가 문제인지 전혀 모르겠는데 도움을 받을 수 있을까요?

계좌 정보가 정상적으로 출력된다면 기본적인 내용은 정상적으로 설정된 것 같은데요...

제가 지금 실행해보니 정상적으로 실행이 되는데요. 말씀하신대로 응답코드도 출력해 보았는데 201로 출력됩니다.

![image](https://user-images.githubusercontent.com/104472342/211192863-dc7e9094-bfb4-4eef-9546-27c0b5ce9314.png)

아무런 메세지가 안나온다는것이 res.status_code 는 200인데 body에 아무런 데이터가 없다는 말씀이시죠??

이상하네요. 보통 에러 메세지라도 나오는데...

[시장가 주문 요청에 실패합니다.](https://docs.upbit.com/docs/faq#%EC%8B%9C%EC%9E%A5%EA%B0%80-%EC%A3%BC%EB%AC%B8-%EC%9A%94%EC%B2%AD%EC%97%90-%EC%8B%A4%ED%8C%A8%ED%95%A9%EB%8B%88%EB%8B%A4)

이런 내용이 있긴한데, 노트북에는 제대로 되어있긴 합니다. 문제가 해결 안될경우 업비트에 문의해 봐야 할 것 같습니다. 아무런 응답이 없는 경우는 저도 겪어 보질 못했어요. 에러라도 응답하는것이 보통이라서요.

**Comment by eolg1574** [comment]
안녕하세요
안그래도 이런 경우를 찾을 수가 없어서 업비트에 문의 메일을 보냈습니다.
 
![계좌정보](https://user-images.githubusercontent.com/61569682/211197244-cedfb91d-d85b-4d44-a5d2-3400ac3bc09e.png)
저 같은 경우에는 계좌 정보까지는 확인이 잘 되는데 주문하기부터 문제가 생깁니다.

![주문하기](https://user-images.githubusercontent.com/61569682/211197285-846f09d7-9612-4710-a5bf-aa9f4c8d33a1.png)
res.status_code는 200이고 아무런 데이터도 받아오지 않습니다.

![주문하기 헤더지움](https://user-images.githubusercontent.com/61569682/211197377-166a1e33-56cf-49c0-95c6-ac47cfb36de1.png)
헤더를 지우면 제대로 오류를 띄웁니다.

![주문하기 query 지움](https://user-images.githubusercontent.com/61569682/211197419-6182e923-5060-4412-88ee-c0f5e4f10442.png)
그런데 query는 내용을 바꿔도 아무런 영향을 주지 않는 것 같습니다.

혹시나 해서 API 레퍼런스 예시를 그대로 복사해서 실행해도 똑같은 문제가 발생하더라구요.

모바일 앱으로는 거래가 잘 이루어져서 계정 자체의 문제도 아닐거라고 생각합니다.

지금은 마땅한 해결책이 없는듯하니 답장이 오는걸 기다려보겠습니다.

**Comment by johnverkim** [comment]
그냥 매수 주문은 잘되나요? API에 주문하기 권한이 없는 것은 아닌지 확인을 위해서 고정가격으로 매수 주문 넣어보는 것도 좋을것 같아요.

**Comment by eolg1574** [comment]
![고정가격매매](https://user-images.githubusercontent.com/61569682/211200883-3aa081da-067e-44ad-ab52-f712336523ae.png)
매수 매도는 전부 먹통입니다.

![주문조회](https://user-images.githubusercontent.com/61569682/211200909-dce34710-b4f6-4933-ac45-2972a5189b2c.png)
이건 앱으로 주문해서 주문 조회 한거고

![주문취소](https://user-images.githubusercontent.com/61569682/211200945-9149a15b-9cc7-4a38-a29c-0a0af0e657cd.png)
그걸 주문 취소한겁니다.

![최근거래내역](https://user-images.githubusercontent.com/61569682/211200969-9ce88e40-16aa-47c6-b1c5-4d1c5de78639.png)
최근 거래 내역까지 잘 나옵니다.

api로 주문만 안되는 상황인 것 같습니다.

**Comment by johnverkim** [comment]
API 생성하실때 '주문하기' 권한 체크 하신거죠? 뭔가 권한이나 그런것이 문제일것 같네요. 데이터가 전달이 안된다기 보다...

**Comment by eolg1574** [comment]
![api 권한](https://user-images.githubusercontent.com/61569682/211223797-d7bdfdd8-eaa2-44b3-895e-428a7d761bb6.png)
그것도 이미 확인 했는데...

권한이 없으면 없다고 에러를 주지 않을까요?

뭐가 문제인지 점점 더 모르겠습니다...

**Comment by eolg1574** [comment]
업비트에서 답장을 해주셨는데 아직 해결되지는 않았습니다.
![업비트 답장1](https://user-images.githubusercontent.com/61569682/211508266-49c3db7a-9eec-4be1-a33e-aec80f563ca3.png)
주문 요청 마켓이 KRW_BTC처럼 잘못 입력되었다는데 이전의 스크린샷을 보면 제대로 입력되어있습니다.
제가 기억하기로는 마켓에는 손을 대지도 않았구요.

제가 입력한 값과 다른 정보가 업비트 서버로 보내질 수 있나요?

![주문하기-레퍼런스 예시 그대로 사용 ](https://user-images.githubusercontent.com/61569682/211515852-ca5bd0dd-78d6-4611-9083-6cc68aa7f1ff.png)
게다가 업비트 레퍼런스의 예시를 그대로 복사해서 실행해도 같은 결과가 나옵니다.

그리고 key를 새로 생성해도 결과가 같았습니다...

다시 문의해보겠습니다.

**Comment by johnverkim** [comment]
계좌 조회, 주문 조회, 주문 취소까지 잘되는데, 주문 생성만 안되는 상황인가요???

**Comment by johnverkim** [comment]
올려주신 내용중에 쿼리 내용을 삭제한 경우 200 리턴하는것이 보이는데...그렇다면 쿼리내용이 잘못 되었을 경우 업비트에서 200을 리턴하고 빈 응답을 주도록 구현되어 있다고 가정할 수 있는것인지...
결국은 테스트를 통해서 차근 차근 디버깅을 해봐야 할 것 같습니다. 쿼리 내용도 다시 확인해 보시구요. smtm 프로젝트의 소스 코드를 그대로 사용해서도 해보세요.

**Comment by eolg1574** [comment]
업비트 측에서 답장 주셨습니다.

![업비트 답장2](https://user-images.githubusercontent.com/61569682/212102330-1020169b-e4de-4298-ac87-f4dc1a84acf6.png)

url encoded body는 아마 urlencoded().encode() 이걸 말하는 것 같은데 일단 작동하니 문제 없다고 생각했습니다.

requests 라이브러리 버전은 저도 최신이었습니다.

하지만 저는 이용 환경이나 라이브러리 동작 여부 검토할 능력이 되지 않으니 그냥 윈도우를 초기화하고 프로그램을 전부 새로 설치했습니다...

![주문성공](https://user-images.githubusercontent.com/61569682/212103491-e49d62a4-0b25-440d-8511-03ec6fbb92dd.png)

코드는 변경하지 않고 그대로 사용했고 성공했습니다.

제 쪽에서 뭔가 문제였던건 맞는 것 같지만 결국 원인을 찾지는 못했습니다.

여러모로 시간만 들이고 원인을 찾지 못해 아쉽네요...

**Comment by johnverkim** [comment]
앗ㅠ 윈도우까지ㅠ
그런 경우를 위해서 venv를 사용하는것이 좋습니다. 새로운 가상환경을 만들어서 해보시고 의심되는 패키지의 버전을 변경해 보는것도 방법입니다.
저도 예전에 비슷한 경험이 있었는데,
데탑에서는 잘되던게 노트북에서 안되서,
패키지 버전을 맞춰서 해결했습니다. 물론 근원적인 원인은 알 수 없었지만...ㅠ
수고하셨습니다.
